# Importing Libraries

In [1]:
import argparse
import hashlib
import os
import pandas as pd

# Loading and Checking the data

In [2]:
df = pd.read_csv("OVERALL CLAIMS PAID ANALYSIS - AUDIT DATE - 202507-11.csv")

# number of rows and columns
rows, cols = df.shape
print(f"Number of Rows : {rows} \nNumber of Columns : {cols}")

Number of Rows : 422382
Number of Columns : 30

In [3]:
# top of the data
df.head()

,POLICY CODE,PLAN NAME,MEMBERSHIP NO,PATIENT NAME,PRINCIPAL MEMBER,PAYEE,CLAIM DATE,CLAIM TYPE,PAYMENT FROM,PROVIDER NAME,...,INV AMOUNT,PAYABLE AMOUNT,NOTES,GROUP NAME,BENEFIT CODE,CLAIM SUB TYPE,ICD CODE,CLAIM AUDIT DATE,SERVICE DATE,STATUS
0,KEA1B1/21/PD087/000001/02,SMEC INTERNATIONAL PTY LIMITED,UK09931800,MS ROSE RACHEL ATIENO OPIYO,MS ROSE RACHEL ATIENO OPIYO,EQUITY AFIA LIMITED (KE),25/11/2025,OP,insured,EQUITY AFIA LIMITED (KE),...,5000.0,5000.0,p,SMEC INTERNATIONAL PTY LIMITED,ANNUAL MEDICAL CHECK-UP,ANNUAL MEDICAL CHECKUP,Z00.0,25/11/2025,28/04/2025,AUDITED
1,TANATHIWSBS/08,TANATHI WATER SERVICES BOARD [STAFF],UK06606100,MR LESHINKA LEMAMAI NKARINKA,MR LESHINKA LEMAMAI NKARINKA,EQUITY AFIA LIMITED (KE),25/11/2025,OP,insured,EQUITY AFIA LIMITED (KE),...,15000.0,15000.0,p,TANATHI WATER WORKS DEVELOPMENT AGENCY (STAFF),OPTICAL,OPTICAL,H52.1,25/11/2025,26/06/2025,AUDITED
2,KEA1B1/21/PC514/000001/03,HAND IN HAND EASTERN AFRICA,UK08084802,MASTER SETH MUTAI KITONGA,MR SAMUEL KITONGA MUNYITHYA,EQUITY AFIA LIMITED (KE),25/11/2025,OP,insured,EQUITY AFIA LIMITED (KE),...,2900.0,500.0,p,HAND IN HAND EASTERN AFRICA,OUT-PATIENT,OUT-PATIENT,Z51.9,25/11/2025,3/3/2025,AUDITED
3,KEA1B1/21/PC514/000001/03,HAND IN HAND EASTERN AFRICA,UK09899600,MR MAXWEL KIPLANGAT NGETICH,MR MAXWEL KIPLANGAT NGETICH,EQUITY AFIA LIMITED (KE),25/11/2025,OP,insured,EQUITY AFIA LIMITED (KE),...,5230.0,5230.0,p,HAND IN HAND EASTERN AFRICA,OUT-PATIENT,OUT-PATIENT,Z51.9,25/11/2025,3/3/2025,AUDITED
4,KEA1B1/21/PC514/000001/03,HAND IN HAND EASTERN AFRICA,UK08073000,MR BENSON CHOLE LUGWIRI,MR BENSON CHOLE LUGWIRI,EQUITY AFIA LIMITED (KE),25/11/2025,OP,insured,EQUITY AFIA LIMITED (KE),...,3050.0,3050.0,p,HAND IN HAND EASTERN AFRICA,OUT-PATIENT,OUT-PATIENT,Z51.9,25/11/2025,4/3/2025,AUDITED

In [4]:
# bottom of the data
df.tail()

,POLICY CODE,PLAN NAME,MEMBERSHIP NO,PATIENT NAME,PRINCIPAL MEMBER,PAYEE,CLAIM DATE,CLAIM TYPE,PAYMENT FROM,PROVIDER NAME,...,INV AMOUNT,PAYABLE AMOUNT,NOTES,GROUP NAME,BENEFIT CODE,CLAIM SUB TYPE,ICD CODE,CLAIM AUDIT DATE,SERVICE DATE,STATUS
422377,KEHPCA/01,KENYA HOSPICE AND PALLIATIVE CARE ASSOC,7224095-00,MIRIAM MUHONJA IGOBWA,MIRIAM MUHONJA IGOBWA,NAIROBI HOSPITAL (10468KE),30/08/2018,IP,insured,NAIROBI HOSPITAL (10468KE),...,6400.0,6400.0,p,KENYA HOSPICE AND PALLIATIVE CARE ASSOC,IN-PATIENT,GENERAL HOSPITALIZATION,D05,30/08/2018,1/12/2016,PAID
422378,BHANJIZS/02,AFYAIMARA SENIOR MEDICAL COVER,8183333-00,ZUBEDA SADRUDIN BHANJI,ZUBEDA SADRUDIN BHANJI,THE AGA KHAN UNIVERSITY HOSPITALNAIROBI (10461KE),15/05/2019,OP,insured,THE AGA KHAN UNIVERSITY HOSPITALNAIROBI (10461KE),...,6200.0,6200.0,PAYABLE,NaN,OUT-PATIENT,OUT-PATIENT,M54.4,15/05/2019,31/12/2016,PAID
422379,NAIVAS/02,NAIVAS LIMITED,8551332-02,JEREMY NJAAGA KIMANI,KIMANI DAVID,DR DONALD P. OYATSI (10825KE),6/5/2019,OP,self fund,DR DONALD P. OYATSI (10825KE),...,3000.0,3000.0,pay,NAIVAS LIMITED,OUT-PATIENT,OUT-PATIENT,G40.6,43621,14/03/2018,PAID
422380,EABL/02,EAST AFRICA BREWERIES LTD STAFF MEDICAL,02108324-00,KAMUNYE ANNE WAMBUI,KAMUNYE ANNE WAMBUI,NAIROBI HOSPITAL (10468KE),31/01/2019,OP,self fund,NAIROBI HOSPITAL (10468KE),...,9800.0,9800.0,PAY,EAST AFRICA BREWERIES LTD STAFF MEDICAL,OUT-PATIENT,OUT-PATIENT,Z36.9,31/01/2019,8/10/2016,PAID
422381,BASFEAL/01,BASF EAST AFRICA LIMITED,02175146-03,JANICE MUTHONI,PATRICK WAINAINA NGUGI,DR B.J. NATHWANI (77330KE),19/01/2019,OP,self fund,DR B.J. NATHWANI (77330KE),...,1200.0,1200.0,P,BASF EAST AFRICA LIMITED,DENTAL,DENTAL,K02,19/01/2019,10/9/2016,PAID

In [5]:
# check the datatypes in the dataset
df.dtypes

POLICY CODE          object
PLAN NAME            object
MEMBERSHIP NO        object
PATIENT NAME         object
PRINCIPAL MEMBER     object
PAYEE                object
CLAIM DATE           object
CLAIM TYPE           object
PAYMENT FROM         object
PROVIDER NAME        object
DOCTOR              float64
SERVICE              object
DIAGNOSIS CODE       object
DIAGNOSIS            object
INVOICE NUMBER       object
CLAIM NO             object
PROD CURRENCY        object
INVOICE AMOUNT      float64
SETTLED AMOUNT      float64
INV CURRENCY         object
INV AMOUNT          float64
PAYABLE AMOUNT      float64
NOTES                object
GROUP NAME           object
BENEFIT CODE         object
CLAIM SUB TYPE       object
ICD CODE             object
CLAIM AUDIT DATE     object
SERVICE DATE         object
STATUS               object
dtype: object

NUMERIC COLUMNS: DOCTOR, INVOICE AMOUNT, SETTLED AMOUNT, INV AMOUNT, PAYABLE AMOUNT

NON-NUMERIC COLUMNS: 'POLICY CODE', 'PLAN NAME', 'MEMBERSHIP NO', 'PATIENT NAME', 'PRINCIPAL MEMBER', 'PAYEE', 
                    'CLAIM DATE', 'CLAIM TYPE', 'PAYMENT FROM', 'PROVIDER NAME', 'SERVICE', 'DIAGNOSIS CODE', 'DIAGNOSIS','INVOICE NUMBER', 'CLAIM NO', 'PROD CURRENCY', 'INV CURRENCY', 'NOTES', 'GROUP NAME', 'BENEFIT CODE', 'CLAIM SUB TYPE', 'ICD CODE', 'CLAIM AUDIT DATE', 'SERVICE DATE', 'STATUS'.

In [6]:
# general information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422382 entries, 0 to 422381
Data columns (total 30 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   POLICY CODE       422382 non-null  object
 1   PLAN NAME         422055 non-null  object
 2   MEMBERSHIP NO     422055 non-null  object
 3   PATIENT NAME      422055 non-null  object
 4   PRINCIPAL MEMBER  422058 non-null  object
 5   PAYEE             422381 non-null  object
 6   CLAIM DATE        422382 non-null  object
 7   CLAIM TYPE        422382 non-null  object
 8   PAYMENT FROM      422382 non-null  object
 9   PROVIDER NAME     422382 non-null  object
 10  DOCTOR            0 non-null       float64
 11  SERVICE           422382 non-null  object
 12  DIAGNOSIS CODE    413046 non-null  object
 13  DIAGNOSIS         417436 non-null  object
 14  INVOICE NUMBER    422382 non-null  object
 15  CLAIM NO          422382 non-null  object
 16  PROD CURRENCY     422382 non-null  object
 17  INVOICE AMOUNT    422382 non-null  float64
 18  SETTLED AMOUNT    422382 non-null  float64
 19  INV CURRENCY      422382 non-null  object
 20  INV AMOUNT        422382 non-null  float64
 21  PAYABLE AMOUNT    422382 non-null  float64
 22  NOTES             422351 non-null  object
 23  GROUP NAME        391799 non-null  object
 24  BENEFIT CODE      422381 non-null  object
 25  CLAIM SUB TYPE    422382 non-null  object
 26  ICD CODE          417436 non-null  object
 27  CLAIM AUDIT DATE  422382 non-null  object
 28  SERVICE DATE      422382 non-null  object
 29  STATUS            422382 non-null  object
dtypes: float64(5), object(25)
memory usage: 96.7+ MB

In [7]:
# check for missing data
nulls = df.isnull().sum()
nulls[nulls > 0].sort_values(ascending=False)

DOCTOR              422382
GROUP NAME           30583
DIAGNOSIS CODE        9336
DIAGNOSIS             4946
ICD CODE              4946
PLAN NAME              327
MEMBERSHIP NO          327
PATIENT NAME           327
PRINCIPAL MEMBER       324
NOTES                   31
PAYEE                    1
BENEFIT CODE             1
dtype: int64

**Observations:**
- `DOCTOR` is 100% null — drop or ignore in features.
- `DIAGNOSIS CODE` and `ICD CODE` have ~ 9K and ~5K nulls respectively.

# Anonymize the data

Drop direct identifiers, hash the membership number so per-member patterns stay trackable.

In [8]:
# need to drop direct identifier columns(patient name, principal member, membership number, claim number, etc.) and quasi identifier columns (date of birth, address, etc.) to protect patient privacy.

personal_info_cols = ["PATIENT NAME", "PRINCIPAL MEMBER", "MEMBERSHIP NO", "INVOICE NUMBER", "CLAIM NO", "POLICY CODE"]
df[personal_info_cols].sample(10)

,PATIENT NAME,PRINCIPAL MEMBER,MEMBERSHIP NO,INVOICE NUMBER,CLAIM NO,POLICY CODE
43677,MR ISAIAH MUCHIRA GICHERU,MR ISAIAH MUCHIRA GICHERU,UK09705600,114872#000,RC2310161568,KEA1B1/21/PD033/000001/03
87615,MR KANYI KIURU,MR KANYI KIURU,OK15773800,10198442#000,RC23101210284,EABL/09
203249,MRS GRACE NYAWIRA MBAU,MR JOSEPH ONSOMU ABWANDA,OK15060601,UH281833475_1#000,RC23081116276,KEA1B1/23/PE857/000001/01
81720,MR PRIMUS CHE CHI,MR PRIMUS CHE CHI,OK12933500,OPR113261/23#000,RC23100310485,KEA1B1/22/PE144/000001/01
170479,MISS ADA MASITSA BULIMO,MR PETER BULIMO,OK13534201,IPF-69446#000,DP2307260013,KEA1B1/22/PE327/000001/01
173423,MS CHRISTINE WANJIRU KARIUKI,MS CHRISTINE WANJIRU KARIUKI,OK14686300,UH281903484_1#000,RC23092411939,KEA1B1/22/PE142/000001/01
337,MASTER SHAWN ALEXIS NYAMAI,MR EDWARD NYAMAI KITHUKA,UK11396703,EQA-02000-34739#002,RC2311222369,KEA1B1/22/PD566/000001/01
191999,MRS FATUMA ABDI ISSACK,MRS FATUMA ABDI ISSACK,UK04622900,UH281860981_3#000,RC23082312244,KEA1B1/19/PA911/000001/05
211800,MRS TERESA NABWIRE ACHOLA,MR DANIEL MBOYA NYAUKE,UK11211201,ORE176945/23#000,RC23080710732,KEA1B1/17/PA227/000001/07
419941,MR PAUL AMARAH ASIENGA,MR PAUL AMARAH ASIENGA,UK09853000,OINO220603100#001,RC22090310771,KEA1B1/21/PD052/000001/01

In [9]:
# Drop direct identifiers
df = df.drop(columns=["PATIENT NAME", "PRINCIPAL MEMBER"])

# Hash MEMBERSHIP NO, INVOICE NO, CLAIM NO — keeps per-member grouping possible without exposing the real ID
df['hash_membership_no'] = df['MEMBERSHIP NO'].apply(lambda x: hashlib.sha256(str(x).encode()).hexdigest()[:12] if pd.notna(x) else "unknown")
df['hash_invoice_no'] = df['INVOICE NUMBER'].apply(lambda x: hashlib.sha256(str(x).encode()).hexdigest()[:12] if pd.notna(x) else "unknown")    #preserves duplicate detection, prevents re-identification
df['hash_claim_no'] = df['CLAIM NO'].apply(lambda x: hashlib.sha256(str(x).encode()).hexdigest()[:12] if pd.notna(x) else "unknown")
df['hash_policy_code'] = df['POLICY CODE'].apply(lambda x: hashlib.sha256(str(x).encode()).hexdigest()[:12] if pd.notna(x) else "unknown")

df = df.drop(columns=["MEMBERSHIP NO", "INVOICE NUMBER", "CLAIM NO", "POLICY CODE"])

print(f"Anonymised DataFrame shape: {df.shape}")
print(f"Sample of anonymised DataFrame:\n{df[['hash_claim_no', 'hash_invoice_no', 'hash_membership_no', 'hash_policy_code']].sample(10)}")

Anonymised DataFrame shape: (422382, 28)
Sample of anonymised DataFrame:
       hash_claim_no hash_invoice_no hash_membership_no hash_policy_code
145923  2eb529717072    2a9e1a985cb8       5041692235ac     beb5741e7a0e
128336  6cfdeaa28f6a    484baf998f76       e93028070a4f     29f4ddc3ef31
163628  5234c1ffe971    cdd0d08256ed       6bdab1d87354     8d826d27d643
215928  d9f6f419b0d7    8fafda8ce9f3       22fc965180e3     b8a171130582
10518   23d70cd7f919    772eaff94bf7       a174693f3f6d     c1f7d8b8c263
28740   385ac5e5344d    87dfc2511981       9969151e780d     74526c23082d
51259   158f1d15683c    b0084077f50a       b59b5be444bb     a34e2646aa1c
392143  b1ba5781daf5    4fad8e5476f2       78005f0ef1bc     12b8ed838025
296698  d300c67e477d    e2279831ab08       5b33962971fa     34c3328cea6d
212646  6e324f6bce23    f2d491740f0b       1a561ebd0b65     61392f549dbd

In [10]:
# save the anonymised dataset
df.to_csv("anonymised_claims_data.csv", index=False)

# Data Cleaning

In [11]:
# load the anonymised dataset
df_anonymised = pd.read_csv("anonymised_claims_data.csv")
print(f"Anonymised DataFrame shape: {df_anonymised.shape}")

Anonymised DataFrame shape: (422382, 28)

## Strip white spaces, lowercase and replace spaces with underscores

In [12]:
# strip whitespace from column names, lowercase, replace spaces with underscores
df_anonymised.columns = df_anonymised.columns.str.strip().str.lower().str.replace(' ', '_')
df_anonymised.columns

Index(['plan_name', 'payee', 'claim_date', 'claim_type', 'payment_from',
       'provider_name', 'doctor', 'service', 'diagnosis_code', 'diagnosis',
       'prod_currency', 'invoice_amount', 'settled_amount', 'inv_currency',
       'inv_amount', 'payable_amount', 'notes', 'group_name', 'benefit_code',
       'claim_sub_type', 'icd_code', 'claim_audit_date', 'service_date',
       'status', 'hash_membership_no', 'hash_invoice_no', 'hash_claim_no',
       'hash_policy_code'],
      dtype='object')

## Date-type conversion

In [13]:
df_anonymised.dtypes

plan_name              object
payee                  object
claim_date             object
claim_type             object
payment_from           object
provider_name          object
doctor                float64
service                object
diagnosis_code         object
diagnosis              object
prod_currency          object
invoice_amount        float64
settled_amount        float64
inv_currency           object
inv_amount            float64
payable_amount        float64
notes                  object
group_name             object
benefit_code           object
claim_sub_type         object
icd_code               object
claim_audit_date       object
service_date           object
status                 object
hash_membership_no     object
hash_invoice_no        object
hash_claim_no          object
hash_policy_code       object
dtype: object

In [14]:
# check the date columns in the data
df_anonymised[['claim_date', 'claim_audit_date', 'service_date']].sample(15)

        claim_date claim_audit_date service_date
142214    1/9/2025            45666   25/08/2025
416618   4/10/2024            45392    3/10/2024
152966  28/08/2025       28/08/2025   26/06/2025
327390  19/06/2025       19/06/2025   19/06/2025
30248   24/10/2025       24/10/2025   17/10/2025
264340  13/07/2025       13/07/2025   13/07/2025
15415    5/11/2025            45788    4/11/2025
20025   31/10/2025       31/10/2025   31/10/2025
44169   16/10/2025       16/10/2025   16/10/2025
231666  26/07/2025       26/07/2025   22/07/2025
368712  27/05/2025       27/05/2025   27/05/2025
75063   29/09/2025       29/09/2025   29/09/2025
276622    9/7/2025            45907     7/7/2025
34253   23/10/2025       23/10/2025   20/10/2025
189940  13/08/2025       13/08/2025   13/08/2025

In [15]:
# dates columns are parsed as strings, so we need to convert them to datetime objects for analysis
for date_cols in ['claim_date', 'claim_audit_date', 'service_date']:
# convert them to datetime objects
    df_anonymised[date_cols]= pd.to_datetime(df_anonymised[date_cols],errors='coerce', dayfirst=True)
    failed = df_anonymised[date_cols].isna().sum()
    print(f"{date_cols:20s}: {failed:>7,} failed to parse (now NaT)")

claim_date          :       0 failed to parse (now NaT)
claim_audit_date    : 158,539 failed to parse (now NaT)
service_date        :       4 failed to parse (now NaT)

In [16]:
# First, parse normally as strings
# Now catch the ones that failed by trying them as Excel serial numbers
mask = df_anonymised['claim_audit_date'].isna()

# Pull the raw values back from the original column — adjust the source df name
excel_serials = pd.to_numeric(df.loc[mask, 'CLAIM AUDIT DATE'], errors='coerce')

# Excel epoch (accounting for the famous 1900 leap year bug)
excel_dates = pd.Timestamp('1899-12-30') + pd.to_timedelta(excel_serials, unit='D')

# Merge back
df_anonymised.loc[mask, 'claim_audit_date'] = excel_dates.values

# Verify
remaining_failures = df_anonymised['claim_audit_date'].isna().sum()
print(f"Remaining failures after Excel fix: {remaining_failures:,}")

Remaining failures after Excel fix: 0

In [17]:
raw_service_dates = pd.read_csv('OVERALL CLAIMS PAID ANALYSIS - AUDIT DATE - 202507-11.csv',usecols=['SERVICE DATE'])['SERVICE DATE']

# Find the same indices that failed to parse in the anonymised cleaned df
mask = df_anonymised['service_date'].isna()
print("Raw SERVICE DATE values for the failed rows:")
print(raw_service_dates[mask].tolist())
print()
print("Unique values:", raw_service_dates[mask].unique())

Raw SERVICE DATE values for the failed rows:
['29/02/2022', '29/02/2022', '29/02/2022', '29/02/2022']

Unique values: ['29/02/2022']

For the year 2022, the date 29-02-2022 did not exist because it was not a leap year. This could be a manual data entry issue, or an actual case of fraud if in case these claims were paid out.

In [18]:
# Flag rows with impossible/invalid service dates BEFORE we lose them
df_anonymised['service_date_invalid'] = df_anonymised['service_date'].isna().astype(int)

# Investigate before deciding what to do
invalid_mask = df_anonymised['service_date_invalid'] == 1
print(f"Invalid service date rows: {invalid_mask.sum()}")
print(f"  Total exposure (settled): KES {df_anonymised.loc[invalid_mask, 'settled_amount'].sum():,.2f}")
print(f"  Status breakdown:\n{df_anonymised.loc[invalid_mask, 'status'].value_counts()}")
print(f"  All paid?: {(df_anonymised.loc[invalid_mask, 'settled_amount'] > 0).all()}")

# Back-fill so downstream features (claim_lag_days, etc.) don't break
# Use claim_date as the fallback — this gives lag=0, which is conservative.
# The fraud signal is preserved in service_date_invalid=1.
df_anonymised['service_date'] = df_anonymised['service_date'].fillna(df_anonymised['claim_date'])

Invalid service date rows: 4
  Total exposure (settled): KES 30,047.70
  Status breakdown:
status
AUDITED    4
Name: count, dtype: int64
  All paid?: True

## Duplicate entries

Remove all fully duplicated rows

In [19]:
print(f"Rows before dropping duplicates: {len(df_anonymised)}")
# drop exact duplicate entries
df_anonymised = df_anonymised.drop_duplicates(keep='first').reset_index(drop=True)
print(f"DataFrame shape after dropping duplicates: {df_anonymised.shape[0]}")

Rows before dropping duplicates: 422382
DataFrame shape after dropping duplicates: 422374

In [22]:
print(df_anonymised.sample(5))

                                       plan_name  \
182536                  AFYAIMARA  FAMILY COVER
237590           INVENTURE MOBILE LIMITED (TALA)
362824                              WORLD VISION
273503  KEMRI WELLCOME TRUST RESEARCH PROGRAMME
116790                    UNTAPPED WATER LIMITED

                                                    payee claim_date  \
182536                   PATHCARE KENYA LIMITED (11277KE) 2025-08-16
237590        KILIMANI CHILDREN`S CLINIC (DR.MOSES LANGO) 2025-07-25
362824                           EQUITY AFIA LIMITED (KE) 2025-06-01
273503                 MEPHI HEALTH SERVICES LIMITED (KE) 2025-07-10
116790  THE AGA KHAN UNIVERSITY HOSPITALNAIROBI (10461KE) 2025-09-13

       claim_type payment_from  \
182536         OP      insured
237590         OP      insured
362824         OP    self fund
273503         OP      insured
116790         OP      insured

                                            provider_name  doctor  \
182536                   PATHCARE KENYA LIMITED (11277KE)     NaN
237590        KILIMANI CHILDREN`S CLINIC (DR.MOSES LANGO)     NaN
362824                           EQUITY AFIA LIMITED (KE)     NaN
273503                 MEPHI HEALTH SERVICES LIMITED (KE)     NaN
116790  THE AGA KHAN UNIVERSITY HOSPITALNAIROBI (10461KE)     NaN

                                                  service  \
182536              ALBUMIN URINE MICROALBUMIN QUAN,FULL
237590  CONSULTANT,Adol 250mg Suppositories,Orelox 40m...
362824  CONSULTANT,Cetamol 500mg tablets,ASCORIL SYRUP...
273503  CONSULTANT,Metronidazole 400mg Tablets,Aclotas P
116790                       INJECTION ADMINISTRATION FEE

                   diagnosis_code  \
182536  OTHERS
237590  OTHERS
362824  OTHERS
273503  OTHERS
116790  OTHERS

                                                diagnosis  ... claim_sub_type  \
182536  Diabetes mellitus (E10-E14) [ Diabetes mellitu...  ...    OUT-PATIENT
237590        Tinea barbae and tinea capitis [ Mycoses  ]  ...    OUT-PATIENT
362824  Plasmodium falciparum malaria, unspecified [ P...  ...    OUT-PATIENT
273503  Malaria due to simian plasmodia [ Protozoal di...  ...    OUT-PATIENT
116790  Noninfective gastroenteritis and colitis, unsp...  ...    OUT-PATIENT

        icd_code  claim_audit_date service_date  status  hash_membership_no  \
182536       E10        2025-08-16   2025-08-16    PAID        4c121ed1620a
237590     B35.0        2025-07-25   2025-07-24    PAID        ebcd09fe9f54
362824     B50.9        2025-01-06   2025-06-01    PAID        6fb421364ac4
273503     B53.1        2025-10-07   2025-07-10    PAID        4b8778b19234
116790     K52.9        2025-09-13   2025-09-13    PAID        859609a15491

       hash_invoice_no hash_claim_no hash_policy_code service_date_invalid
182536    1f73e24e4bf5  478780a65df3     d12b85e547fe                    0
237590    b2cc885cda10  c0d5d42cc226     63d4e4dbfebc                    0
362824    3e8cdaa71962  b24d968e90e6     03f5ba938f21                    0
273503    c4d48e19030a  df5ed1ab88e6     6d33fadf0cd3                    0
116790    6e1820a7818f  5139062ecf21     95aa823b05da                    0

[5 rows x 29 columns]

In [24]:
# check the currency columns
print(f"\nCurrency distribution (INV CURRENCY):")
print(df_anonymised['inv_currency'].value_counts())

print(f"\nCurrency distribution (PROD CURRENCY):")
print(df_anonymised['prod_currency'].value_counts())

Currency distribution (INV CURRENCY):
inv_currency
KES    418913
UGX      2254
TZS       736
USD       265
RWF       190
SSP        13
-           3
Name: count, dtype: int64

Currency distribution (PROD CURRENCY):
prod_currency
KES    422197
UGX       174
-           3
Name: count, dtype: int64

The different currencies would result in extreme outliers which may affect the analysis and modelling phase. As we are working with Kenyan context, we will filter to remain with only KES currency.

In [25]:
# Filter to KES only — checking both currency columns to be safe
kes_mask = ((df_anonymised['prod_currency'] == 'KES') & (df_anonymised['inv_currency'] == 'KES'))

df_anonymised = df_anonymised[kes_mask].reset_index(drop=True)
print(f"Anonymised data after filtering to only KES currency: {df_anonymised.shape[0]} rows")

Anonymised data after filtering to only KES currency: 418913 rows

In [26]:
# check the unique currency in both columns - should be KES only
print(f"Unique prod_currency: {df_anonymised['prod_currency'].unique()}")
print(f"Unique inv_currency : {df_anonymised['inv_currency'].unique()}")

Unique prod_currency: ['KES']
Unique inv_currency : ['KES']

In [27]:
# redundant columns - inv_currency, prod_currency can be dropped

# check if invoice_amount and inv_amount are the same
print(f"prod_currency == inv_currency: {(df_anonymised['prod_currency'] == df_anonymised['inv_currency']).all()}")
print(f"invoice_amount == inv_amount: {(df_anonymised['invoice_amount'] == df_anonymised['inv_amount']).all()}")

prod_currency == inv_currency: True
invoice_amount == inv_amount: False

In [29]:
diff_mask = df_anonymised['invoice_amount'] != df_anonymised['inv_amount']
print(f"Rows with invoice_amount != inv_amount: {diff_mask.sum():,} ({diff_mask.mean():.1%})")

# How big are the discrepancies?
df_anonymised['amount_adjustment'] = df_anonymised['invoice_amount'] - df_anonymised['inv_amount']

print(f"\nAdjustment statistics (invoice_amount - inv_amount):")
print(df_anonymised.loc[diff_mask, 'amount_adjustment'].describe())

# Direction of the adjustment
adjustments_up   = (df_anonymised['amount_adjustment'] > 0).sum()
adjustments_down = (df_anonymised['amount_adjustment'] < 0).sum()
print(f"\nAdjustments UP   (invoice_amount > inv_amount): {adjustments_up:,}")
print(f"Adjustments DOWN (invoice_amount < inv_amount): {adjustments_down:,}")

# Sample a few
print("\nLargest 5 upward adjustments:")
print(df_anonymised.nlargest(10, 'amount_adjustment')[
    ['hash_claim_no','service','invoice_amount','inv_amount','settled_amount','status','notes']
].to_string())

Rows with invoice_amount != inv_amount: 2,070 (0.5%)

Adjustment statistics (invoice_amount - inv_amount):
count      2070.000000
mean      14483.196855
std       61158.288868
min      -24830.360000
25%        1916.000000
50%        3635.000000
75%        7346.500000
max      976656.000000
Name: amount_adjustment, dtype: float64

Adjustments UP   (invoice_amount > inv_amount): 1,975
Adjustments DOWN (invoice_amount < inv_amount): 95

Largest 5 upward adjustments:
       hash_claim_no                                        service  invoice_amount  inv_amount  settled_amount     status                      notes
20577   afb267042c90                     ADMISSION FEES,SBP,SBP,SBP        976656.0         0.0             0.0  CANCELLED          PAY#wrong benefit
20578   afb267042c90                     ADMISSION FEES,SBP,SBP,SBP        976656.0         0.0             0.0  CANCELLED          PAY#wrong benefit
20579   afb267042c90                     ADMISSION FEES,SBP,SBP,SBP        976656.0         0.0             0.0  CANCELLED          PAY#wrong benefit
146975  ae5487ac041f                  ADMISSION FEES,ADMISSION FEES        880112.0         0.0             0.0  CANCELLED        PAY#SCHEME REVERSAL
220623  11d1ea42730f                                SURGEON,SURGEON        785000.0         0.0             0.0  CANCELLED  PAY#OVERPAID TO REPROCESS
264371  946890d211e6                  ADMISSION FEES,ADMISSION FEES        632138.0         0.0             0.0  CANCELLED                     PAY#SR
51519   c4285e7caf73                                 ADMISSION FEES        570441.0         0.0             0.0  CANCELLED    PAY#reprocess indemnity
220546  a0e76aaed185                                 ADMISSION FEES        564583.0         0.0             0.0  CANCELLED              PAY#REPROCESS
405326  b18cfeb450a5  CONSULTANT,DENTAL POLISHING,DENTAL FILLING,X-        564000.0         0.0             0.0  CANCELLED           p#WRONG CURRENCY
220626  11d1ea42730f                  ADMISSION FEES,ADMISSION FEES        466067.0         0.0             0.0  CANCELLED  PAY#OVERPAID TO REPROCESS

Since invoice_amount and inv_amount are not equal, it is worth intvestigating to find out why or how this happens.

**Proxy fraud definition** 

A claim is "suspicious" if the insurer settled less than 80% of what was invoiced

Add a new feature: had_pre_audit_adjustment (binary). The fact that an adjustment was needed is itself a weak fraud signal — it means the original submission wasn't right

In [33]:
# has_pre_audit_adjustment for invoice_amount not equal to inv_amount
df_anonymised['had_pre_audit_adjustment'] = (df_anonymised['invoice_amount'] != df_anonymised['inv_amount']).astype(int)

# an entry is suspicious if the settled_amount is less than 80% of the invoice_amount
df_anonymised['is_suspicious'] = (df_anonymised['settled_amount'] < df_anonymised['invoice_amount'] * 0.80).astype(int)

# # Compare suspicion rates between claims that had a pre-audit adjustment and claims that didn't
# adjusted_group     = df_anonymised[df_anonymised['had_pre_audit_adjustment'] == 1]
# not_adjusted_group = df_anonymised[df_anonymised['had_pre_audit_adjustment'] == 0]

# # For each group, count what fraction is suspicious:
# print(f"Fraud rate when invoice amount is adjusted: {(adjusted_group['settled_amount'] < adjusted_group['invoice_amount'] * 0.80).mean()}")

# print(f"Fraud rate when invoice amount not adjusted: {(not_adjusted_group['settled_amount'] < not_adjusted_group['invoice_amount'] * 0.80).mean()}")

print("Fraud rate by pre-audit adjustment status:")
print(df_anonymised.groupby('had_pre_audit_adjustment')['is_suspicious'].agg(fraud_rate='mean',claim_count='count'))

Fraud rate by pre-audit adjustment status:
                          fraud_rate  claim_count
had_pre_audit_adjustment
0                           0.100102       416843
1                           0.916425         2070

If a claim needed to be adjusted before audit, the original submission was already off in some way. That "offness" might correlate with the later signal that fraud detectors care about (over-billing, vague codes, etc.) 

This is a proxy fraud rate, not a true fraud rate. We're using "settled < 80% of invoice" as a stand-in for "the insurer detected something off" — because no labelled fraud data exists.

## Missing values

In [34]:
df_anonymised.isnull().sum()

plan_name                      313
payee                            1
claim_date                       0
claim_type                       0
payment_from                     0
provider_name                    0
doctor                      418913
service                          0
diagnosis_code                9246
diagnosis                     4936
prod_currency                    0
invoice_amount                   0
settled_amount                   0
inv_currency                     0
inv_amount                       0
payable_amount                   0
notes                           31
group_name                   30483
benefit_code                     1
claim_sub_type                   0
icd_code                      4936
claim_audit_date                 0
service_date                     0
status                           0
hash_membership_no               0
hash_invoice_no                  0
hash_claim_no                    0
hash_policy_code                 0
service_date_invalid             0
amount_adjustment                0
had_pre_audit_adjustment         0
is_suspicious                    0
dtype: int64

Same number of rows missing for both icd_code and diagnosis. -> A null ICD code on a claim that still got paid is itself a fraud signal: how can you settle a claim with no diagnosis?

In [36]:
# track null icd_codes before filling them

df_anonymised['icd_code_missing'] = df_anonymised['icd_code'].isna().astype(int)

In [37]:
# Categorical fills with meaningful defaults
df_anonymised['plan_name']   = df_anonymised['plan_name'].fillna('UNKNOWN')         # fill with unknown
df_anonymised['group_name']  = df_anonymised['group_name'].fillna('INDIVIDUAL')     # fill with individual for missing group name( likely means the policy is individual (not part of a corporate or association group))
df_anonymised['icd_code']    = df_anonymised['icd_code'].fillna('UNKNOWN')          # fill with unknown
df_anonymised['diagnosis']   = df_anonymised['diagnosis'].fillna('UNKNOWN')         # fill with unknown
df_anonymised['payee']       = df_anonymised['payee'].fillna('UNKNOWN')             # fill with unknown
df_anonymised['notes']       = df_anonymised['notes'].fillna('')                    # fill with an empty string

# Drop rows with missing benefit_code
df_anonymised = df_anonymised[df_anonymised['benefit_code'].notna()].reset_index(drop=True)


df_anonymised.isnull().sum()

plan_name                        0
payee                            0
claim_date                       0
claim_type                       0
payment_from                     0
provider_name                    0
doctor                      418913
service                          0
diagnosis_code                9246
diagnosis                        0
prod_currency                    0
invoice_amount                   0
settled_amount                   0
inv_currency                     0
inv_amount                       0
payable_amount                   0
notes                            0
group_name                       0
benefit_code                     1
claim_sub_type                   0
icd_code                         0
claim_audit_date                 0
service_date                     0
status                           0
hash_membership_no               0
hash_invoice_no                  0
hash_claim_no                    0
hash_policy_code                 0
service_date_invalid             0
amount_adjustment                0
had_pre_audit_adjustment         0
is_suspicious                    0
icd_code_missing                 0
dtype: int64

In [38]:
df_anonymised['diagnosis_code'].value_counts()

diagnosis_code
OTHERS                       409667
Name: count, dtype: int64

Since all other entries of diagnosis_code are "OTHERS". We will fill the missing values with "OTHERS" and then drop the "doctor" because it is completely null in all entries.

In [39]:
# fill diagnosis_code with "OTHERS" for missing values
df_anonymised['diagnosis_code'] = df_anonymised['diagnosis_code'].fillna('OTHERS')

# drop doctor column
df_anonymised = df_anonymised.drop(columns=['doctor'])

print(df_anonymised.isnull().sum())

# save the cleaned and anonymised dataset
df_anonymised.to_csv("anonymised_claims_data_cleaned.csv", index=False)

plan_name                   0
payee                       0
claim_date                  0
claim_type                  0
payment_from                0
provider_name               0
service                     0
diagnosis_code              0
diagnosis                   0
prod_currency               0
invoice_amount              0
settled_amount              0
inv_currency                0
inv_amount                  0
payable_amount              0
notes                       0
group_name                  0
benefit_code                1
claim_sub_type              0
icd_code                    0
claim_audit_date            0
service_date                0
status                      0
hash_membership_no          0
hash_invoice_no             0
hash_claim_no               0
hash_policy_code            0
service_date_invalid        0
amount_adjustment           0
had_pre_audit_adjustment    0
is_suspicious               0
icd_code_missing            0
dtype: int64